// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:clinicease/main.dart';
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/widgets.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
    // Your app's main code
  runApp(const MyApp());
}


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZezNPTYcUt8QXpcx7LCroP84jXgk8dyY',
    appId: '1:1013081124961:web:7067e669c5dd358a40ba20',
    messagingSenderId: '1013081124961',
    projectId: 'clinicease-d1dc6',
    authDomain: 'clinicease-d1dc6.firebaseapp.com',
    storageBucket: 'clinicease-d1dc6.appspot.com',
    measurementId: 'G-1GFVSRLT9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeus6bvA-wZG-kWSwaiSitzj2pe9UkNK4',
    appId: '1:1013081124961:android:cdbe5afbc9abc49140ba20',
    messagingSenderId: '1013081124961',
    projectId: 'clinicease-d1dc6',
    storageBucket: 'clinicease-d1dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXNrgJUIVLtyKy0gXbSaGZTFLYr2-Hfg',
    appId: '1:1013081124961:ios:99b17531a746edbc40ba20',
    messagingSenderId: '1013081124961',
    projectId: 'clinicease-d1dc6',
    storageBucket: 'clinicease-d1dc6.appspot.com',
    iosBundleId: 'com.example.clinicease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiXNrgJUIVLtyKy0gXbSaGZTFLYr2-Hfg',
    appId: '1:1013081124961:ios:65ee2efbc19456f040ba20',
    messagingSenderId: '1013081124961',
    projectId: 'clinicease-d1dc6',
    storageBucket: 'clinicease-d1dc6.appspot.com',
    iosBundleId: 'com.example.clinicease.RunnerTests',
  );
}
